export * from './blockchainController.service';
import { BlockchainControllerService } from './blockchainController.service';
export * from './bookingController.service';
import { BookingControllerService } from './bookingController.service';
export * from './commentController.service';
import { CommentControllerService } from './commentController.service';
export * from './meetingController.service';
import { MeetingControllerService } from './meetingController.service';
export * from './moduleController.service';
import { ModuleControllerService } from './moduleController.service';
export * from './newsController.service';
import { NewsControllerService } from './newsController.service';
export * from './postController.service';
import { PostControllerService } from './postController.service';
export * from './projectController.service';
import { ProjectControllerService } from './projectController.service';
export * from './projectDocumentController.service';
import { ProjectDocumentControllerService } from './projectDocumentController.service';
export * from './projectUserController.service';
import { ProjectUserControllerService } from './projectUserController.service';
export * from './reactionController.service';
import { ReactionControllerService } from './reactionController.service';
export * from './taskController.service';
import { TaskControllerService } from './taskController.service';
export * from './trendingController.service';
import { TrendingControllerService } from './trendingController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './voteController.service';
import { VoteControllerService } from './voteController.service';
export * from './workspaceController.service';
import { WorkspaceControllerService } from './workspaceController.service';
export * from './workspaceMessageController.service';
import { WorkspaceMessageControllerService } from './workspaceMessageController.service';
export const APIS = [BlockchainControllerService, BookingControllerService, CommentControllerService, MeetingControllerService, ModuleControllerService, NewsControllerService, PostControllerService, ProjectControllerService, ProjectDocumentControllerService, ProjectUserControllerService, ReactionControllerService, TaskControllerService, TrendingControllerService, UserControllerService, VoteControllerService, WorkspaceControllerService, WorkspaceMessageControllerService];
