/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Post } from './post';


export interface Comment { 
    id?: number;
    content?: string;
    date?: string;
    sentimentType?: Comment.SentimentTypeEnum;
    post?: Post;
    user?: User;
}
export namespace Comment {
    export type SentimentTypeEnum = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
    export const SentimentTypeEnum = {
        Positive: 'POSITIVE' as SentimentTypeEnum,
        Neutral: 'NEUTRAL' as SentimentTypeEnum,
        Negative: 'NEGATIVE' as SentimentTypeEnum
    };
}


