/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VoteDTO } from './voteDTO';


export interface CommentDTO { 
    id?: number;
    postId?: number;
    userId?: number;
    content?: string;
    author?: string;
    sentiment?: CommentDTO.SentimentEnum;
    votes?: Array<VoteDTO>;
    date?: string;
}
export namespace CommentDTO {
    export type SentimentEnum = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
    export const SentimentEnum = {
        Positive: 'POSITIVE' as SentimentEnum,
        Neutral: 'NEUTRAL' as SentimentEnum,
        Negative: 'NEGATIVE' as SentimentEnum
    };
}


