/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Workspace } from './workspace';


export interface Organization { 
    organization_id?: number;
    name?: string;
    address?: string;
    phone_number?: string;
    email?: string;
    workspace?: Workspace;
    created_at?: string;
    updated_at?: string;
    is_deleted?: boolean;
}

