/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ImageEntity } from './imageEntity';


export interface Post { 
    id?: number;
    content?: string;
    date?: string;
    sentimentType?: Post.SentimentTypeEnum;
    title?: string;
    image?: ImageEntity;
    user?: User;
    upvotes?: number;
}
export namespace Post {
    export type SentimentTypeEnum = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
    export const SentimentTypeEnum = {
        Positive: 'POSITIVE' as SentimentTypeEnum,
        Neutral: 'NEUTRAL' as SentimentTypeEnum,
        Negative: 'NEGATIVE' as SentimentTypeEnum
    };
}


