/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { ProjectDocument } from './projectDocument';


export interface ProjectModuleProjection { 
    priority?: number;
    title?: string;
    description?: string;
    deadline?: string;
    documents?: Set<ProjectDocument>;
    beginDate?: string;
    achievement?: number;
    project?: Project;
    moduleId?: number;
}

