/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectProjection } from './projectProjection';
import { UserProjection } from './userProjection';


export interface ProjectUserProjection { 
    role?: ProjectUserProjection.RoleEnum;
    user?: UserProjection;
    project?: ProjectProjection;
}
export namespace ProjectUserProjection {
    export type RoleEnum = 'MANAGER' | 'TEAM_MEMBER';
    export const RoleEnum = {
        Manager: 'MANAGER' as RoleEnum,
        TeamMember: 'TEAM_MEMBER' as RoleEnum
    };
}


