/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { News } from './news';


export interface Reaction { 
    reactionId?: number;
    reactionType?: Reaction.ReactionTypeEnum;
    reactionDate?: string;
    user?: User;
    news?: News;
}
export namespace Reaction {
    export type ReactionTypeEnum = 'LAUGHEMOJI' | 'WOWEMOJI' | 'HEART' | 'LOVEEMOJI' | 'LIKE' | 'SHOKEDEMOJI' | 'SADEMOJI';
    export const ReactionTypeEnum = {
        Laughemoji: 'LAUGHEMOJI' as ReactionTypeEnum,
        Wowemoji: 'WOWEMOJI' as ReactionTypeEnum,
        Heart: 'HEART' as ReactionTypeEnum,
        Loveemoji: 'LOVEEMOJI' as ReactionTypeEnum,
        Like: 'LIKE' as ReactionTypeEnum,
        Shokedemoji: 'SHOKEDEMOJI' as ReactionTypeEnum,
        Sademoji: 'SADEMOJI' as ReactionTypeEnum
    };
}


