/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Votable { 
    id?: number;
    content?: string;
    date?: string;
    sentimentType?: Votable.SentimentTypeEnum;
}
export namespace Votable {
    export type SentimentTypeEnum = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
    export const SentimentTypeEnum = {
        Positive: 'POSITIVE' as SentimentTypeEnum,
        Neutral: 'NEUTRAL' as SentimentTypeEnum,
        Negative: 'NEGATIVE' as SentimentTypeEnum
    };
}


