/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Organization } from './organization';


export interface Workspace { 
    workspaceId?: number;
    name?: string;
    description?: string;
    image?: string;
    organization?: Organization;
    projects?: Set<Project>;
    createdAt?: string;
    updatedAt?: string;
    locked?: boolean;
}

