/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Feedback } from '../../models/feedback';

export interface MarkFeedbackAsRead$Params {
  feedbackId: number;
}

export function markFeedbackAsRead(http: HttpClient, rootUrl: string, params: MarkFeedbackAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<Feedback>> {
  const rb = new RequestBuilder(rootUrl, markFeedbackAsRead.PATH, 'put');
  if (params) {
    rb.path('feedbackId', params.feedbackId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Feedback>;
    })
  );
}

markFeedbackAsRead.PATH = '/feedbacks/{feedbackId}/mark-as-read';
