/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkspaceProjection {
  createdAt?: string;
  description?: string;
  image?: string;
  isLocked?: boolean;
  name?: string;
  workspaceId?: number;
}
