/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectResponse } from '../models/project-response';
import { WorkspaceProjection } from '../models/workspace-projection';
export interface WorkspaceResponse {
  projectResponse?: ProjectResponse;
  projection?: WorkspaceProjection;
}
