/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageResponse } from '../../models/message-response';

export interface GetWorkspaceMessages$Params {
  workspaceId: number;
  size: number;
  page_no: number;
}

export function getWorkspaceMessages(http: HttpClient, rootUrl: string, params: GetWorkspaceMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageResponse>> {
  const rb = new RequestBuilder(rootUrl, getWorkspaceMessages.PATH, 'get');
  if (params) {
    rb.path('workspaceId', params.workspaceId, {});
    rb.path('size', params.size, {});
    rb.path('page_no', params.page_no, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageResponse>;
    })
  );
}

getWorkspaceMessages.PATH = '/ws-msg/get-workspace-messages/{workspaceId}/{size}/{page_no}';
