/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserProjection } from '../models/user-projection';
export interface MeetingProjection {
  admin?: UserProjection;
  beginDate?: string;
  createdAt?: string;
  description?: string;
  endDate?: string;
  meetingId?: number;
  members?: Array<UserProjection>;
  title?: string;
}
