/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectDocument } from '../models/project-document';
import { UserDto } from '../models/user-dto';
export interface MessageDto {
  attachments?: Array<ProjectDocument>;
  createdAt?: string;
  message?: string;
  sender?: UserDto;
}
