/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskRequest } from '../models/task-request';
export interface ModuleRequest {
  achievement?: number;
  beginDate?: string;
  deadline?: string;
  description?: string;
  priority?: number;
  tasks?: Array<TaskRequest>;
  title?: string;
}
