/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Organization {
  address?: string;
  created_at?: string;
  email?: string;
  name?: string;
  organizationId?: number;
  phone_number?: string;
  updated_at?: string;
}
