/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Workspace } from '../models/workspace';
export interface Organization {
  address?: string;
  created_at?: string;
  email?: string;
  is_deleted?: boolean;
  name?: string;
  organizationId?: number;
  phone_number?: string;
  updated_at?: string;
  workspace?: Workspace;
}
