/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectDocument {
  created_at?: string;
  document_id?: number;
  document_name?: string;
  document_type?: 'IMAGE' | 'OTHER';
  path?: string;
  updated_at?: string;
}
