/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModuleRequest } from '../models/module-request';
export interface ProjectRequest {
  achievement?: number;
  beginDate?: string;
  deadline?: string;
  description?: string;
  modules?: Array<ModuleRequest>;
  name?: string;
  priority?: number;
  status?: 'NOT_STARTED' | 'IN_PROGRESS' | 'ON_HOLD' | 'CANCELED' | 'UNDER_REVIEW' | 'FINISHED';
  workspace_id?: number;
}
