/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectProjection } from '../models/project-projection';
export interface ProjectResponse {
  isLast?: boolean;
  pageNo?: number;
  pageSize?: number;
  projection?: Array<ProjectProjection>;
  totalElements?: number;
  totalPages?: number;
}
