/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskProjection } from '../models/task-projection';
export interface TaskResponse {
  isLast?: boolean;
  pageNo?: number;
  pageSize?: number;
  projections?: Array<TaskProjection>;
  totalElements?: number;
  totalPages?: number;
}
