/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProjection {
  email?: string;
  full_name?: string;
  image?: string;
  userId?: number;
}
