/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Project } from '../models/project';
import { ProjectDocument } from '../models/project-document';
import { ProjectModule } from '../models/project-module';
import { Task } from '../models/task';
import { Workspace } from '../models/workspace';
export interface WorkspaceMessage {
  attachments?: Array<ProjectDocument>;
  createdAt?: string;
  message?: string;
  messageId?: number;
  module?: ProjectModule;
  project?: Project;
  task?: Task;
  updatedAt?: string;
  workspace?: Workspace;
}
