/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentRequest } from '../../models/document-request';
import { Task } from '../../models/task';

export interface AddTaskToProject$Params {
  project_id: number;
      body?: {
'task': Task;
'documents_request'?: Array<DocumentRequest>;
'documents'?: Array<Blob>;
}
}

export function addTaskToProject(http: HttpClient, rootUrl: string, params: AddTaskToProject$Params, context?: HttpContext): Observable<StrictHttpResponse<Task>> {
  const rb = new RequestBuilder(rootUrl, addTaskToProject.PATH, 'post');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Task>;
    })
  );
}

addTaskToProject.PATH = '/task/add-task-project/{project_id}';
