/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Project } from '../../models/project';

export interface AddProjectToWorkspace$Params {
  workspace_id: number;
      body?: {
'project': Project;
'image'?: Blob;
}
}

export function addProjectToWorkspace(http: HttpClient, rootUrl: string, params: AddProjectToWorkspace$Params, context?: HttpContext): Observable<StrictHttpResponse<Project>> {
  const rb = new RequestBuilder(rootUrl, addProjectToWorkspace.PATH, 'post');
  if (params) {
    rb.path('workspace_id', params.workspace_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Project>;
    })
  );
}

addProjectToWorkspace.PATH = '/project/add-project-workspace/{workspace_id}';
