/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeetingProjection } from '../../models/meeting-projection';

export interface GetMeetingById$Params {
  meeting_id: number;
}

export function getMeetingById(http: HttpClient, rootUrl: string, params: GetMeetingById$Params, context?: HttpContext): Observable<StrictHttpResponse<MeetingProjection>> {
  const rb = new RequestBuilder(rootUrl, getMeetingById.PATH, 'get');
  if (params) {
    rb.path('meeting_id', params.meeting_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeetingProjection>;
    })
  );
}

getMeetingById.PATH = '/meeting/get-meeting/{meeting_id}';
