/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganizationEntityCountsDto {
  feedbackCount?: number;
  officeCount?: number;
  organizationId?: number;
  organizationName?: string;
  userCount?: number;
}
