/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  accountis_enabled?: boolean;
  accountis_locked?: boolean;
  address?: string;
  birth_date?: string;
  created_at?: string;
  email?: string;
  first_name?: string;
  full_name?: string;
  image?: string;
  last_name?: string;
  password?: string;
  phone_number?: string;
  reset_pwd_code?: string;
  reset_pwd_date?: string;
  updated_at?: string;
  user_id?: number;
}
