/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Services } from '../../models/services';

export interface UpdateService$Params {
  id: number;
      body: Services
}

export function updateService(http: HttpClient, rootUrl: string, params: UpdateService$Params, context?: HttpContext): Observable<StrictHttpResponse<Services>> {
  const rb = new RequestBuilder(rootUrl, updateService.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Services>;
    })
  );
}

updateService.PATH = '/services/update/{id}';
