/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AddDocumentsToProjectAutomation$Params {
  project_id: number;
  doc_name: string;
      body?: {
'document': Blob;
}
}

export function addDocumentsToProjectAutomation(http: HttpClient, rootUrl: string, params: AddDocumentsToProjectAutomation$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, addDocumentsToProjectAutomation.PATH, 'post');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('doc_name', params.doc_name, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

addDocumentsToProjectAutomation.PATH = '/project-document/add-documents-project-automation/{project_id}/{doc_name}';
