/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Post } from './post';


export interface Comment { 
    id?: number;
    content?: string;
    date?: string;
    post?: Post;
    user?: User;
}

