/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ImageEntity } from './imageEntity';


export interface Post { 
    id?: number;
    content?: string;
    date?: string;
    title?: string;
    image?: ImageEntity;
    user?: User;
}

