/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    user_id?: number;
    firs_name?: string;
    last_name?: string;
    full_name?: string;
    birth_date?: string;
    image?: string;
    address?: string;
    password?: string;
    reset_pwd_code?: string;
    reset_pwd_date?: string;
    phone_number?: string;
    email?: string;
    created_at?: string;
    updated_at?: string;
    is_deleted?: boolean;
    is_locked?: boolean;
}

