/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Organization } from './organization';


export interface Workspace { 
    workspace_id?: number;
    name?: string;
    description?: string;
    image?: string;
    organization?: Organization;
    created_at?: string;
    updated_at?: string;
    is_locked?: boolean;
    is_deleted?: boolean;
}

