/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectModule } from '../../models/project-module';

export interface UpdateModule$Params {
  module_id: number;
      body: ProjectModule
}

export function updateModule(http: HttpClient, rootUrl: string, params: UpdateModule$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectModule>> {
  const rb = new RequestBuilder(rootUrl, updateModule.PATH, 'patch');
  if (params) {
    rb.path('module_id', params.module_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectModule>;
    })
  );
}

updateModule.PATH = '/project-module/update-module/{module_id}';
