/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskResponse } from '../../models/task-response';

export interface GetTaskByProject$Params {
  project_id: number;
  size: number;
  page_no: number;
}

export function getTaskByProject(http: HttpClient, rootUrl: string, params: GetTaskByProject$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskResponse>> {
  const rb = new RequestBuilder(rootUrl, getTaskByProject.PATH, 'get');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('size', params.size, {});
    rb.path('page_no', params.page_no, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskResponse>;
    })
  );
}

getTaskByProject.PATH = '/task/get-task-by-project/{project_id}/{size}/{page_no}';
