/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Service } from './service';


export interface Booking { 
    id?: number;
    reference?: string;
    status?: string;
    user?: User;
    service?: Service;
    created_at?: string;
    updated_at?: string;
}

