/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookingResponseDTO { 
    id?: number;
    reference?: string;
    status?: string;
    userId?: number;
    userName?: string;
    serviceId?: number;
    serviceName?: string;
    createdAt?: string;
    updatedAt?: string;
    blockchainVerified?: boolean;
}

