/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentRequest { 
    document_name?: string;
    doc_type?: DocumentRequest.DocTypeEnum;
}
export namespace DocumentRequest {
    export type DocTypeEnum = 'IMAGE' | 'OTHER';
    export const DocTypeEnum = {
        Image: 'IMAGE' as DocTypeEnum,
        Other: 'OTHER' as DocTypeEnum
    };
}


