/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Meeting { 
    meetingId?: number;
    title?: string;
    description?: string;
    members?: Set<User>;
    admin?: User;
    beginDate?: string;
    endDate?: string;
    createdAt?: string;
    updatedAt?: string;
    formattedDate?: string;
    formattedTime?: string;
}

