/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDocument } from './projectDocument';
import { UserProjection } from './userProjection';


export interface MessageProjection { 
    message?: string;
    sender?: UserProjection;
    createdAt?: string;
    attachments?: Array<ProjectDocument>;
}

