/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageProjection } from './messageProjection';


export interface MessageResponse { 
    messages?: Array<MessageProjection>;
    pageNo?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
    isLast?: boolean;
}

