/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleRequest } from './moduleRequest';


export interface ProjectRequest { 
    name?: string;
    description?: string;
    priority?: number;
    workspace_id?: number;
    achievement?: number;
    beginDate?: string;
    deadline?: string;
    status?: ProjectRequest.StatusEnum;
    modules?: Array<ModuleRequest>;
}
export namespace ProjectRequest {
    export type StatusEnum = 'NOT_STARTED' | 'IN_PROGRESS' | 'ON_HOLD' | 'CANCELED' | 'UNDER_REVIEW' | 'FINISHED';
    export const StatusEnum = {
        NotStarted: 'NOT_STARTED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        OnHold: 'ON_HOLD' as StatusEnum,
        Canceled: 'CANCELED' as StatusEnum,
        UnderReview: 'UNDER_REVIEW' as StatusEnum,
        Finished: 'FINISHED' as StatusEnum
    };
}


