/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { User } from './user';
import { ProjectUserId } from './projectUserId';


export interface ProjectUser { 
    id?: ProjectUserId;
    role?: ProjectUser.RoleEnum;
    project?: Project;
    user?: User;
    created_at?: string;
    updated_at?: string;
}
export namespace ProjectUser {
    export type RoleEnum = 'MANAGER' | 'TEAM_MEMBER';
    export const RoleEnum = {
        Manager: 'MANAGER' as RoleEnum,
        TeamMember: 'TEAM_MEMBER' as RoleEnum
    };
}


