/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDocument } from './projectDocument';


export interface ProjectProjection { 
    name?: string;
    priority?: number;
    description?: string;
    status?: ProjectProjection.StatusEnum;
    image?: string;
    deadline?: string;
    documents?: Set<ProjectDocument>;
    beginDate?: string;
    projectId?: number;
    achievement?: number;
}
export namespace ProjectProjection {
    export type StatusEnum = 'NOT_STARTED' | 'IN_PROGRESS' | 'ON_HOLD' | 'CANCELED' | 'UNDER_REVIEW' | 'FINISHED';
    export const StatusEnum = {
        NotStarted: 'NOT_STARTED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        OnHold: 'ON_HOLD' as StatusEnum,
        Canceled: 'CANCELED' as StatusEnum,
        UnderReview: 'UNDER_REVIEW' as StatusEnum,
        Finished: 'FINISHED' as StatusEnum
    };
}


