/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskRequest { 
    title?: string;
    description?: string;
    priority?: number;
    beginDate?: string;
    deadline?: string;
    status?: TaskRequest.StatusEnum;
}
export namespace TaskRequest {
    export type StatusEnum = 'TO_DO' | 'IN_PROGRESS' | 'BLOCKED' | 'REWORK_NEEDED' | 'DONE' | 'ARCHIVED';
    export const StatusEnum = {
        ToDo: 'TO_DO' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Blocked: 'BLOCKED' as StatusEnum,
        ReworkNeeded: 'REWORK_NEEDED' as StatusEnum,
        Done: 'DONE' as StatusEnum,
        Archived: 'ARCHIVED' as StatusEnum
    };
}


