/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { ProjectModule } from './projectModule';
import { User } from './user';
import { ProjectDocument } from './projectDocument';


export interface Task { 
    taskId?: number;
    title?: string;
    description?: string;
    priority?: number;
    beginDate?: string;
    deadline?: string;
    project?: Project;
    module?: ProjectModule;
    documents?: Set<ProjectDocument>;
    members?: Set<User>;
    status?: Task.StatusEnum;
    createdAt?: string;
    updatedAt?: string;
    formattedDateTime?: string;
}
export namespace Task {
    export type StatusEnum = 'TO_DO' | 'IN_PROGRESS' | 'BLOCKED' | 'REWORK_NEEDED' | 'DONE' | 'ARCHIVED';
    export const StatusEnum = {
        ToDo: 'TO_DO' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Blocked: 'BLOCKED' as StatusEnum,
        ReworkNeeded: 'REWORK_NEEDED' as StatusEnum,
        Done: 'DONE' as StatusEnum,
        Archived: 'ARCHIVED' as StatusEnum
    };
}


