/**
 * Cloud nine - queute - ESPRIT PI 4ArcTic
 *
 * Contact: mohamedouerfelli3@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDTO { 
    fullName?: string;
    email?: string;
    image?: string;
    role?: UserDTO.RoleEnum;
}
export namespace UserDTO {
    export type RoleEnum = 'MANAGER' | 'TEAM_MEMBER';
    export const RoleEnum = {
        Manager: 'MANAGER' as RoleEnum,
        TeamMember: 'TEAM_MEMBER' as RoleEnum
    };
}


