/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workspace } from '../../models/workspace';

export interface CreateWorkspace$Params {
      body?: {
'workspace': Workspace;
'image'?: Blob;
}
}

export function createWorkspace(http: HttpClient, rootUrl: string, params?: CreateWorkspace$Params, context?: HttpContext): Observable<StrictHttpResponse<Workspace>> {
  const rb = new RequestBuilder(rootUrl, createWorkspace.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Workspace>;
    })
  );
}

createWorkspace.PATH = '/workspace/add-workspace';
