/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workspace } from '../../models/workspace';
import { WorkspaceRequest } from '../../models/workspace-request';

export interface UpdateWorkspace$Params {
  workspace_id: number;
      body?: {
'request'?: WorkspaceRequest;
'image'?: Blob;
}
}

export function updateWorkspace(http: HttpClient, rootUrl: string, params: UpdateWorkspace$Params, context?: HttpContext): Observable<StrictHttpResponse<Workspace>> {
  const rb = new RequestBuilder(rootUrl, updateWorkspace.PATH, 'patch');
  if (params) {
    rb.path('workspace_id', params.workspace_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Workspace>;
    })
  );
}

updateWorkspace.PATH = '/workspace/update-workspace/{workspace_id}';
