/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Office } from '../../models/office';

export interface GetOfficeById$Params {
  id: number;
}

export function getOfficeById(http: HttpClient, rootUrl: string, params: GetOfficeById$Params, context?: HttpContext): Observable<StrictHttpResponse<Office>> {
  const rb = new RequestBuilder(rootUrl, getOfficeById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Office>;
    })
  );
}

getOfficeById.PATH = '/offices/{id}';
