/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Office } from '../../models/office';

export interface GetAllOfficesByOrganisationId$Params {
  organisationId: number;
}

export function getAllOfficesByOrganisationId(http: HttpClient, rootUrl: string, params: GetAllOfficesByOrganisationId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Office>>> {
  const rb = new RequestBuilder(rootUrl, getAllOfficesByOrganisationId.PATH, 'get');
  if (params) {
    rb.path('organisationId', params.organisationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Office>>;
    })
  );
}

getAllOfficesByOrganisationId.PATH = '/offices/by-organisation/{organisationId}';
