/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Office } from './models/office';
export type { Organization } from './models/organization';
export type { Services } from './models/services';
