/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteProjectUser$Params {
  project_id: number;
  user_email: string;
}

export function deleteProjectUser(http: HttpClient, rootUrl: string, params: DeleteProjectUser$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, deleteProjectUser.PATH, 'delete');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('user_email', params.user_email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

deleteProjectUser.PATH = '/project-user/delete-project-user/{project_id}/{user_email}';
