/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectUserResponse } from '../../models/project-user-response';

export interface GetProjects$Params {
  user_id: number;
  size: number;
  page_no: number;
}

export function getProjects(http: HttpClient, rootUrl: string, params: GetProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectUserResponse>> {
  const rb = new RequestBuilder(rootUrl, getProjects.PATH, 'get');
  if (params) {
    rb.path('user_id', params.user_id, {});
    rb.path('size', params.size, {});
    rb.path('page_no', params.page_no, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectUserResponse>;
    })
  );
}

getProjects.PATH = '/project-user/get-projects/{user_id}/{size}/{page_no}';
