/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectUserProjection } from '../../models/project-user-projection';

export interface GetProjectUser$Params {
  project_id: number;
  user_email: string;
}

export function getProjectUser(http: HttpClient, rootUrl: string, params: GetProjectUser$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectUserProjection>> {
  const rb = new RequestBuilder(rootUrl, getProjectUser.PATH, 'get');
  if (params) {
    rb.path('project_id', params.project_id, {});
    rb.path('user_email', params.user_email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectUserProjection>;
    })
  );
}

getProjectUser.PATH = '/project-user/get-project-user/{user_email}/{project_id}';
